# Generated by Django 5.2.3 on 2025-06-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospede',
            old_name='cpf',
            new_name='CPF',
        ),
    ]
