# Generated by Django 5.2.3 on 2025-06-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_rename_cpf_hospede_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospede',
            name='CPF',
            field=models.CharField(max_length=11),
        ),
    ]
