# Generated by Django 5.2.3 on 2025-06-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_hospede_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospede',
            old_name='dataNascimento',
            new_name='data_nascimento',
        ),
    ]
